# Generated by Django 4.2.6 on 2023-10-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lostperson', '0003_rename_color_color_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostperson',
            name='location',
        ),
    ]
