# Generated by Django 4.2.6 on 2023-10-26 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('lostperson', '0003_rename_color_color_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sighting_location', models.CharField(max_length=100)),
                ('sighting_timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('contact_information', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sighting_images/')),
                ('lost_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lostperson.lostperson')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser')),
            ],
        ),
    ]
