# Generated by Django 4.2.6 on 2023-10-26 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='sighting_location',
        ),
    ]
