# Generated by Django 4.2.6 on 2023-10-26 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_location'),
        ('sightings', '0003_sighting_sighting_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='reported_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.customuser'),
        ),
    ]
