# Generated by Django 4.2.6 on 2023-10-26 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_alter_sighting_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='reported_by',
        ),
    ]
